services:
  spring-backend:
    build:
      context: .
      dockerfile: 'dockerfiles/backend/Dockerfile'
    depends_on:
      - postgres

  nginx-services:
    image: 'rapidfort/nginx-official:1.25.5-alpine3.19-perl'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/:/etc/nginx/ssl/
    ports:
      - '443'
    depends_on:
      - spring-backend

  postgres:
    image: 'rapidfort/postgresql-official:17.4-alpine3.21'
    environment:
      - 'POSTGRES_DB=dayguard'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ### For security reasons, we should not expose the database to the outside world
    # ports:
    #   - '5432'
    ### Uncomment the above lines to expose the database to the outside world (NOT RECOMMENDED)