name: Deploy DayGuard

permissions:
  contents: write
  packages: write

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    environment:
      name: Deploy backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./dockerfiles/backend/Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/day-fit/florae:latest

  deploy-frontend:
    runs-on: ubuntu-latest

    environment:
      name: Deploy frontend
      url: https://dayguard.dayfit.pl

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --mode production

      - name: Write SSH key to file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key

      - name: Deploy to production
        run: rsync -avz --delete -e "ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/home/deploy/app/